import IP from './IPConfig'
// 接口
const API = {
  // 单个上传图片到阿里云OSS
  UPLOAD_UPLOADIMG: 'web/upload/uploadImg',
  // 登录
  USER_LOGIN: 'web/user/login',
  // 获取学校学生信息
  STUDENT_GETSTUDENTINFO: 'web/student/getStudentsInfo',
  // 根据条件获取学校学生信息
  STUDENT_GETSTUDENTSBY: 'web/student/getStudentsBy',
  // 批量导入学生信息
  STUDENT_IMPORTSTUDENT: 'web/student/importStudents',
  // 下载学生模版
  STUDENT_DOWNLOADTEMPLATE: 'web/student/downloadTemplate',
  // 导出学生信息
  STUDENT_EXPORTSTUDENTS: 'web/student/exportStudents',
  // 单个新增学生信息
  STUDENT_ADDSTUDENT: 'web/student/addStudent',
  // 删除学生信息
  STUDENT_DELSTUDENT: 'web/student/delStudent',
  // 批量删除学生信息
  STUDENT_DELSTUDENTS: 'web/student/delStudents',
  // 查询学生信息
  STUDENT_FINDCONDITIONSTUDENT: 'web/student/findConditionStudent',
  // 更新学生信息
  STUDENT_UPDATESTUDENT: 'web/student/updateStudent',
  // 获取角色信息
  ROLE_GETROLES: 'web/role/getRoles',
  // 下载模版
  TEACHER_DOWNLOADTEMPLATE: 'web/teacher/downloadTemplate',
  // 导出教师信息
  TEACHER_EXPORTTEACHERS: 'web/teacher/exportTeachers',
  // 添加老师信息
  TEACHER_ADDTEACHER: 'web/teacher/addTeacher',
  // 删除老师信息
  TEACHER_DELTEACHER: 'web/teacher/delTeacher',
  // 批量删除教师信息
  TEACHER_DELTEACHERS: 'web/teacher/delTeachers',
  // 根据需要的条件查询老师信息
  TEACHER_FINDBYCOMMON: 'web/teacher/findByCommon',
  // 根据条件获取学校老师信息
  TEACHER_GETTEACHERSBY: 'web/teacher/getTeachersBy',
  // 根据条件获取学校老师信息
  TEACHER_TEACHERSBY: 'web/teacher/teachersBy',
  // 获取学校老师信息
  TEACHER_GETTEACHERSINFO: 'web/teacher/getTeachersInfo',
  // 批量导入教师信息
  TEACHER_IMPORTTEACHERS: 'web/teacher/importTeachers',
  // 更新教师信息
  TEACHER_UPDATETEACHER: 'web/teacher/updateTeacher',
  // 查询学校的所有年级
  GRADE_FINDBYGRADES: 'web/grade/findByGrades',
  // 查询学校年级组
  GRADE_GETGRADEGROUP: 'web/grade/getGradeGroup',
  // 根据需要的条件查询年级信息
  GRADE_FINDBYCOMMON: 'web/grade/findByCommon',
  // 获取年级组信息
  GRADE_GETGRADESGROUP: 'web/grade/getGradesGroup',
  // 添加年级组
  GRADE_ADDGRADEGROUP: 'web/grade/addGradeGroup',
  // 删除年级组
  GRADE_DELGRADEGROUP: 'web/grade/delGradeGroup',
  // 更新年级组
  GRADE_UPDATEGRADEGROUP: 'web/grade/updateGradeGroup',
  // 查询所有年级下的班级
  DCCLASS_FINDBYGRADEID: 'web/dcClass/findByGradeId',
  // 查询所有考试模板
  EXAM_FINDBYTEMPLATELIST: 'web/exam/findByTemplateList',
  // 根据模板id查询科目信息
  EXAM_FINDBYTEMSUBCOM: 'web/exam/findByTemsubCom',
  // 创建考试
  EXAM_ESTABLISH: 'web/exam/establish',
  // 修改考试
  EXAM_UPDATEBYID: 'web/exam/updateById',
  // 分页查询考试
  EXAM_HOMEEXAM: 'web/exam/homeExam',
  // 查询所有考试科目
  EXAM_EXAMSUBJECT: 'web/exam/examSubject',
  // 根据条件查询科目信息，不传参数查所有
  EXAM_FINDBYSUBJECTCOM: 'web/exam/findBySubjectCom',
  // 查询科目进度信息和人员信息
  EXAM_SELECTSUBJECT: 'web/exam/selectSubject',
  // 根据考试科目id 查询科目信息
  EXAM_GETEXAMSUBJECT: 'web/exam/getExamSubject',
  // 根据id查询考试信息
  EXAM_FINDBYID: 'web/exam/findByid',
  // 根据考试id查询本次考试的班级数和人数
  EXAM_SELECTCOUNT: 'web/exam/selectCount',
  // 根据id删除考试
  EXAM_DELETEBYID: 'web/exam/deleteById',
  // 添加考试管理员
  EXAM_ADDEXAMADMIN: 'web/exam/addExamAdmin',
  // 添加考试扫描员
  EXAM_ADDEXAMSCANMEBER: 'web/exam/addExamScanMeber',
  // 根据考试id查询考试管理员
  EXAM_FINDBYEXAMADMINCOM: 'web/exam/findByExamAdminCom',
  // 根据考试id查询考试扫描员
  EXAM_FINDBYEXAMSCANCOM: 'web/exam/findByExamScamCom',
  // 根据班级id查询总人数
  EXAM_FINDBYLISTCLASSID: 'web/exam/findByListClassId',
  // 添加考试科目负责人
  EXAM_UPDATETEACHERID: 'web/exam/updateTeacherId',
  // 添加科目
  EXAM_INSERTSUBJECT: 'web/exam/insertSubject',
  // 根据需要的条件查询学校信息
  SCHOOL_FINDBYCOMMON: 'web/school/findByCommon',
  // 根据多个班级id和考试id添加考生信息
  EXAMINEE_ADDEXAMMINEELIST: 'web/examinee/addExammineeList',
  // 单个添加考生
  EXAMINEE_ADDSINGLEEXAMINEE: 'web/examinee/addSingleExaminee',
  // 删除本次考试的所有考生
  EXAMINEE_DELETEBYEXAMID: 'web/examinee/deleteByExamId',
  // 根据id删除考生
  EXAMINEE_DELETEBYID: 'web/examinee/deleteById',
  // 根据id集合删除多个考生信息
  EXAMINEE_DELETELISTBYID: 'web/examinee/deleteListById',
  // 导出考生信息
  EXAMINEE_EXPORTEXAMINEE: 'web/examinee/exportExaminee',
  // 根据条件分页查询考生信息
  EXAMINEE_SELECTCONDITION: 'web/examinee/selectCondition',
  // 从Excel导入考生信息 examId考试id
  EXAMINEEEXCEL_IMPORT: 'web/examineeExcel/import',
  // 使用ftp从服务器上下载 导入考生得模板
  FTP_DOWNLOADFILE: 'web/ftp/downloadFile',
  // 使用ftp上传文件到服务器
  FTP_UPLOAD: 'web/ftp/upload',
  // 新增客观题
  EXAMSTRUCTURE_ADDEXAMSTRUCTURE: 'web/examStructure/AddExamStructure',
  // 新增主观题
  EXAMSTRUCTURE_ADDEXAMS: 'web/examStructure/AddExamS',
  // 根据大题ID删除
  EXAMSTRUCTURE_DELETEBYPRIMARYKEY: 'web/examStructure/deleteByPrimaryKey',
  // 导出设置答案模板
  EXAMSTRUCTURE_EXPORTSETTHEANSWER: 'web/examStructure/exportSettheAnswer',
  // 导入设置答案模板
  EXAMSTRUCTURE_IMPORTANSWERS: 'web/examStructure/importanswers',
  // 上传主观题答案
  EXAMSTRUCTURE_MAINEXAMANSWER: 'web/examStructure/mainExamAnswer',
  // 查询试卷结构(科目id/题型类型(0客观题，1主观题))
  EXAMSTRUCTURE_QUERYEXAMSTRUCTURE: 'web/examStructure/QueryExamStructure',
  // 查询考试成绩
  EXAMSTRUCTURE_QUERYSUMSCORE: 'web/examStructure/QuerySumscore',
  // 设置附加题
  EXAMSTRUCTURE_UPDATEBATCH: 'web/examStructure/updateBatch',
  // 设置答案
  EXAMSTRUCTURE_UPDATEBATCHANSWER: 'web/examStructure/UpdateBatchAnswer',
  // 修改客观题
  EXAMSTRUCTURE_UPDATEBATCHKE: 'web/examStructure/updateBatchKe',
  // 修改主观题
  EXAMSTRUCTURE_UPDATEBATCHZHU: 'web/examStructure/updateBatchZhu',
  // 设置步长分
  EXAMSTRUCTURE_UPDATEBYSTEPSIZE: 'web/examStructure/updateByStepSize',
  // 删除主观题
  EXAMSTRUCTURE_BATCHDELETE: 'web/examStructure/batchDelete',
  // 批量添加题块
  TITLEBLOCK_ADDLIST: 'web/titleBlock/addList',
  // 查询本次考试科目下的题块
  TITLEBLOCK_FINDBYEXAMSUBJECTID: 'web/titleBlock/findByExamSubjectId',
  // 题块任务设置(设置什么就传什么)
  TITLEBLOCK_UPDATECOMMON: 'web/titleBlock/updateCommon',
  // 题块任务设置(设置什么就传什么)
  TITLEBLOCK_UPDATELIST: 'web/titleBlock/updateList',
  // 分配阅卷任务
  TITLEBLOCK_ALLOCATIONTASK: 'web/titleBlock/allocationTask',
  // 批量添加题块坐标
  TOPLIC_ADDLIST: 'web/toplic/addList',
  // 批量修改题块坐标
  TOPLIC_UPDATEBATCH: 'web/toplic/updateBatch',
  // 根据id删除
  TOPLIC_DELETEBYID: 'web/toplic/deleteById',
  // 根据考试科目id 查询 框选坐标
  TOPLIC_FINDBYEXAMSUBJECTID: 'web/toplic/findByExamSubjectId',
  // 添加模板
  EXAMTEMPLATE_ADDEXAMTEMPLATE: 'web/examTemplate/addExamTemplate',
  // 删除 模板
  EXAMTEMPLATE_DELETEANSWER: 'web/examTemplate/deleteAnswer',
  // 删除 答题卡 或试卷图片
  // EXAMTEMPLATE_DELETEEXAMIMG: 'web/examTemplate/deleteExamImg',
  // 查询模板
  EXAMTEMPLATE_FINDBYANSWER: 'web/examTemplate/findByAnsWer',
  // 查询答题卡 和试卷图片
  EXAMTEMPLATE_FINDEXAMIMGLIST: 'web/examTemplate/findExamImgList',
  // 修改模板
  EXAMTEMPLATE_UPDATEBYID: 'web/examTemplate/updateById',
  // 修改 答题卡 或试卷图片
  EXAMTEMPLATE_UPDATEEXAMIMG: 'web/examTemplate/updateExamImg',
  // 添加原题
  ORIGINAL_ADDORIGINAL: 'web/Original/addOriginal',
  // 删除原题
  ORIGINAL_DELETEORIGINAL: 'web/Original/deleteOriginal',
  // 查询原题
  ORIGINAL_GETORIGINAL: 'web/Original/getOriginal',
  // 修改原题
  ORIGINAL_UPDATEORINAL: 'web/Original/updateOriginal',
  // 查询题块
  ORIGINAL_GETQUESTIONBLOCK: 'web/Original/getQuestionBlock',
  // 查询题号
  ORIGINAL_GETTNUMBER: 'web/Original/getTunmber',
  // 查询知识点
  ORIGINAL_GETKNOWLEDGELISTS: 'web/Original/getKnowledgeLists',
  // 删除banner
  BANNER_DELETEBANNER: 'web/banner/deleteBanner',
  // 查询banner
  BANNER_GETBANNER: 'web/banner/getBanner',
  // 新增banner
  BANNER_INSERTBANNER: 'web/banner/insertBanner',
  // 修改banner
  BANNER_UPDATEBANNER: 'web/banner/updateBanner',
  // 删除新闻
  NEWS_DELETENEWS: 'web/news/deleteNews',
  // 删除banner
  NEWS_GETNEWS: 'web/news/getNews',
  // 删除banner
  NEWS_INSERTNEWS: 'web/news/insertNews',
  // 删除banner
  NEWS_UPDATENEWS: 'web/news/updateNews',
  // 新增学校
  ADMINSCHOOL_INSERTSCHOOL: 'web/adminschool/insertSchool',
  // 删除学校
  ADMINSCHOOL_DELSCHOOL: 'web/adminschool/delSchool',
  // 修改学校
  ADMINSCHOOL_UPDATESCHOOL: 'web/adminschool/updateSchool',
  // 获取学校列表
  ADMINSCHOOL_GETSCHOOL: 'web/adminschool/getSchool',
  // 根据年级ID查询学生信息
  ADMINSCHOOL_FINDCLASSBYGRADEID: 'web/dcClass/findClassByGradeId',
  // 根据年级，月份，考试类别，考试名称查询考试
  ADMINSCHOOL_FINDEXAM: 'web/exam/homeExam',
  // 查询角色列表
  ADMINQUERY_ROLELIST: 'web/setMenuRole/getRoleList',
  // 查询菜单列表
  ADMINQUERY_MENULIST: 'web/setMenuRole/getMenuList',
  // 修改菜单
  ADMINEDIT_MENULIST: 'web/setMenuRole/updateMenuListById',
  // 删除菜单
  ADMINDELETE_MENULIST: 'web/setMenuRole/delMenuListById',
  // 新增菜单
  ADMINADD_MENULIST: 'web/setMenuRole/addMenuByParentId',
  // 根据角色ID查询菜单权限
  ADMINQUERY_MENULISTBYROLEID: 'web/setMenuRole/getMenuListByRoleId',
  // 根据角色ID更改菜单列表
  ADMINEDIT_MENULISTBYROLEID: 'web/setMenuRole/updateMenuListByRoleId',
  // 根据角色ID更改菜单列表
  ADMINQUERY_ACCOUNT: 'web/accountManage/getAccountList',
  // 禁用或启用账号
  ADMINSET_ACCOUNTSTATUS: 'web/accountManage/setAccountStatus',
  // 管理员修改密码
  ADMINEDIT_PASSWORD: 'web/accountManage/updateAccountPassword',
  // 用户修改密码
  ADMINUPDATE_PASSWORD: 'web/accountManage/updatePassword',
  // 添加考试科目成绩表传班级ID
  ADMIN_ADDEXAM: 'web/transcript/transcript',
  // 添加考试科目成绩表传考生ID
  ADMIN_ADDEXAMSINGLE: 'web/transcript/transcriptSingle',
  // 根据文件夹名字获取图片列表
  ADMIN_GETIMAGE: 'web/upload/GetFileAllContent',
  // 主观题切图
  ADMIN_SLICING: '/web/examTemplate1/subjectSlicing',
  // 根据文件夹名字获取图片列表
  ADMIN_GETPUBLISHSUBJECTLIST: '/web/exam/getPublishSubjectList/',
  // 单个修改考生信息/web/examinee/updateSingleExaminee
  ADMIN_UPDATESINGLEEXAMINEE: '/web/examinee/updateSingleExaminee',
  // 手动添加选择题答案
  ADMIN_TOP: '/web/examStructure/insertTopicGetscore',
  // 导出学生模板
  ADMIN_STUDENTDOWNLOAD: '/web/student/downloadTemplate',
  // 导出教师模板
  ADMIN_TEACHERDOWNLOAD: '/web/teacher/downloadTemplate',
  // 传json数据给后台
  ADMIN_POSTJSON: '/web/importWrongQuestions/saveObjectByFile',
  // 添加班级
  ADMIN_ADDCLASS: '/web/dcClass/addClass',
  // 获取班级列表
  ADMIN_GETCLASSLIST: '/web/dcClass/getClassList',
  // 乱七八糟
  LUANQIBAZHAO: '/web/importWrongQuestions/saveDcHfsRelation'
}
Object.keys(API).map(key => {
  API[key] = IP.EXAM_IP + API[key]
})
export default API
